In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [3]:
b=a.reshape(2,3,1)

In [4]:
print(b)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


In [5]:
c=np.arange(24).reshape(4,3,2)
print(c)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [6]:
print(np.random.randint(5,100,24).reshape(4,3,2))

[[[58 89]
  [39 48]
  [ 7 86]]

 [[41 78]
  [30 39]
  [22 22]]

 [[23  7]
  [73 67]
  [45 82]]

 [[29 59]
  [11 30]
  [67 98]]]


In [11]:
arr=np.array([[[1,4,7],[2,5,7],[3,6,9]]])
print(arr.flatten())

[1 4 7 2 5 7 3 6 9]


In [13]:
arr=np.array([[[1,4,7],[2,5,7],[3,6,9]]])
print(arr.flatten('F'))

[1 2 3 4 5 6 7 7 9]


In [14]:
arr=np.array([[[1,4,7],[2,5,7],[3,6,9]]])
print(arr.T)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [7]
  [9]]]


In [17]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
a[2:7:2]

array([2, 4, 6])

In [22]:
b=np.arange(12).reshape(1,6,2)
print(b)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]
  [10 11]]]


In [24]:
b[:,2::2,1:2]

array([[[5],
        [9]]])

In [25]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [26]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [27]:
a[-3:1:-1]

array([7, 6, 5, 4, 3, 2])