In [1]:
import numpy as np

In [2]:
a=np.arange(0,5)
print(a)

[0 1 2 3 4]


In [3]:
b=np.arange(1,6)
c=a+b
print(c)

[1 3 5 7 9]


In [4]:
d=a*b
print(d)

[ 0  2  6 12 20]


In [5]:
e=a-b
print(e)

[-1 -1 -1 -1 -1]


In [6]:
f=a/b
print(f)

[0.         0.5        0.66666667 0.75       0.8       ]


In [7]:
g=a-100
print(g)

[-100  -99  -98  -97  -96]


In [8]:
h=1/b
print(h)

[1.         0.5        0.33333333 0.25       0.2       ]


In [9]:
i=a**2
print(i)

[ 0  1  4  9 16]


In [10]:
print(np.sqrt(a))

[0.         1.         1.41421356 1.73205081 2.        ]


In [11]:
print(np.exp(a))

[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


In [12]:
print(np.max(a))

4


In [13]:
print(a.max())

4


In [14]:
a=3
b=5
a=a^b
b=a^b
a=a^b
print(a)
print(b)

5
3


In [15]:
arr=np.array([1,2,3,4])
arr.dtype

dtype('int32')

In [16]:
arr=np.array(['assjbdvhhs','bsjhbdvhcj'])
print(arr.dtype)

<U10


In [17]:
arr=np.array([1.1,2.2,3.3])
arr.dtype

dtype('float64')

In [18]:
arr2=arr.astype('i')
arr2.dtype

dtype('int32')

In [19]:
arr2

array([1, 2, 3], dtype=int32)

In [20]:
arr=np.array([1,0,3])
narr=arr.astype(bool)
print(narr)

[ True False  True]


In [21]:
arr=np.array([[1,2,3,4]])
print(arr.ndim)

2


In [22]:
arr.shape

(1, 4)

In [23]:
arr=np.array([[[1,2,3,4]]])
print(arr.shape)

(1, 1, 4)


In [24]:
print(np.arange(24).reshape(2,3,4))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [25]:
a=np.array([1.0,2.0,3.0])

In [26]:
a.shape

(3,)

In [27]:
a.itemsize

8

In [28]:
a.size

3

In [29]:
a.nbytes

24