In [1]:
import numpy as np

In [2]:
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [3]:
b=np.empty(4)

In [4]:
print(b)

[1. 1. 1. 1.]


In [5]:
c=np.empty(5)
print(c)

[2.12199579e-314 0.00000000e+000 4.42682819e-321 3.79442416e-321
 0.00000000e+000]


In [6]:
d=np.empty((3,4))

In [7]:
print(d)

[[1.30858729e-311 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [6.89903272e-310 4.50140955e+174 2.96014727e-032 1.08646229e-071]
 [3.34945767e-033 1.29255687e+161 2.65099158e-052 1.72345026e-047]]


In [8]:
e=np.random.rand(200)

In [9]:
e

array([0.55434834, 0.12730077, 0.44855256, 0.25422044, 0.52194084,
       0.22304944, 0.92597732, 0.37063251, 0.0317618 , 0.8456304 ,
       0.50571618, 0.11602638, 0.40416612, 0.15620408, 0.18586416,
       0.22451417, 0.43225612, 0.94877463, 0.65730392, 0.66775995,
       0.74915678, 0.1785637 , 0.48623477, 0.38493086, 0.15777358,
       0.63300243, 0.79531011, 0.26181589, 0.70088433, 0.95455288,
       0.09154841, 0.50565894, 0.45503379, 0.14198633, 0.38125288,
       0.02669741, 0.57808141, 0.96123236, 0.82494254, 0.68427402,
       0.54925018, 0.18226602, 0.1363775 , 0.48307906, 0.65656358,
       0.56372863, 0.60075253, 0.70078962, 0.28353731, 0.84023538,
       0.66595331, 0.65735069, 0.40916371, 0.98415256, 0.5748388 ,
       0.40765022, 0.61827625, 0.53625624, 0.83384513, 0.92751268,
       0.63903948, 0.47171505, 0.04434517, 0.28495524, 0.09701441,
       0.5876462 , 0.7384109 , 0.53253099, 0.61612024, 0.55599371,
       0.10507285, 0.27382384, 0.89964167, 0.80891492, 0.14509

In [10]:
f=np.random.randint(5)
print(f)

4


In [11]:
g=np.random.randint(5,100)
print(g)

75


In [12]:
h=np.random.randint(5,100,5)
print(h)

[47 96  6  9 16]


In [13]:
i=np.random.randn(2)
print(i)

[ 0.81800513 -0.9296126 ]


In [14]:
j=np.random.randint(5,100,(2,4))
print(j)

[[44 41 50 37]
 [86  8 44 55]]


In [15]:
k=np.random.randint(5,100,(2,3,4))
print(k)

[[[61 29 52 32]
  [55 86 88 43]
  [74 66 27 48]]

 [[78 46  9 60]
  [94 11 28 84]
  [44 92 79 89]]]


In [16]:
a=[[1,2,3,4],[4,5,6,7]]
arr=np.array(a)
arr

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [22]:
print(np.where(arr%2==0))

(array([0, 0, 1, 1], dtype=int64), array([1, 3, 0, 2], dtype=int64))


In [18]:
i=np.random.randn(2,4)
print(i)

[[ 0.54386198 -1.38181487 -1.41512068 -0.3114995 ]
 [-0.85490847 -0.88347966  0.70835419  0.47655379]]


In [19]:
i=np.random.randn(2,3,4)
print(i)

[[[-0.61277961  1.50795618  1.18365364 -0.53075445]
  [ 0.75900758 -0.71914594  0.11996115 -1.50803691]
  [ 0.73638363  0.67346288  1.62440212 -0.60745472]]

 [[-0.91345043  0.62200635 -0.74591247 -0.63264774]
  [-1.41434744  0.97935568  0.20396709  0.17193114]
  [-0.2798744  -0.27812653  1.55789291  0.5549848 ]]]


In [20]:
i=np.random.rand(2,3)
print(i)

[[0.19375419 0.968676   0.66146367]
 [0.90328928 0.83641045 0.78850957]]


In [21]:
print(np.random.rand(1,5,4))

[[[1.68921008e-02 2.86502508e-01 9.25911385e-01 8.75403134e-01]
  [9.34272397e-01 6.02404400e-04 5.50268534e-01 2.96610612e-01]
  [1.47911621e-01 5.14173257e-01 5.89684656e-01 7.25462051e-01]
  [2.07903254e-01 1.37020955e-01 6.50528770e-01 6.91839418e-02]
  [8.70148563e-01 1.87602539e-01 7.14760784e-01 5.77722178e-02]]]


In [39]:
print(np.logspace(2,3,num=5,base=11))

[ 121.          220.36039471  401.31159963  730.8527479  1331.        ]


In [35]:

print(np.logspace(2,4,num=3,base=2,dtype=int))

[ 4  8 16]


In [40]:
11**2.5

401.31159963300337

In [41]:
np.arange(4)

array([0, 1, 2, 3])

In [46]:
print(np.arange(2,10))

[2 3 4 5 6 7 8 9]


In [47]:
np.arange(3,32,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])