In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)

[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [3]:
print(a[1:])

[[3 4 5]
 [4 5 6]]


In [4]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr[1,1:4]

array([7, 8, 9])

In [5]:
a[:,2]

array([3, 5, 6])

In [6]:
a[:,-1]

array([3, 5, 6])

In [7]:
a[:,-1:]

array([[3],
       [5],
       [6]])

In [8]:
a[:,-1::-1]

array([[3, 2, 1],
       [5, 4, 3],
       [6, 5, 4]])

In [9]:
a[:,::-1]

array([[3, 2, 1],
       [5, 4, 3],
       [6, 5, 4]])

In [10]:
a[::-1,::-1]

array([[6, 5, 4],
       [5, 4, 3],
       [3, 2, 1]])

In [11]:
x=np.array([[1,2],[3,4],[5,6]])

In [12]:
x[[0,1,2],[0,1,0]]

array([1, 4, 5])

In [13]:
y=np.array([[1,2,3],[5,6,7],[9,1,2]])
print(y)

[[1 2 3]
 [5 6 7]
 [9 1 2]]


In [14]:
y[[0,1,2],[0,1,2]]

array([1, 6, 2])

In [15]:
y[1:4,[1,2]]

array([[6, 7],
       [1, 2]])

In [16]:
y[y>5]

array([6, 7, 9])

In [17]:
y>5

array([[False, False, False],
       [False,  True,  True],
       [ True, False, False]])

In [18]:
arr=np.array([2,4,6,8,10])


In [19]:
nc=arr

In [20]:
nc[0]=12

In [21]:
arr

array([12,  4,  6,  8, 10])

In [22]:
nc

array([12,  4,  6,  8, 10])

In [23]:
arr[2]=5

In [24]:
arr

array([12,  4,  5,  8, 10])

In [25]:
nc

array([12,  4,  5,  8, 10])

In [26]:
a=[5,6,7]

In [27]:
b=a

In [28]:
b[0]=9

In [29]:
a

[9, 6, 7]

In [30]:
b

[9, 6, 7]

In [31]:
arr=np.array([1,2,3,4,6,5])


In [32]:
x=arr.copy()

In [33]:
x

array([1, 2, 3, 4, 6, 5])

In [34]:
arr[0]=5

In [35]:
arr

array([5, 2, 3, 4, 6, 5])

In [36]:
x

array([1, 2, 3, 4, 6, 5])

In [37]:
arr=np.array([1,2,3,4,5])

In [38]:
x=arr.view()

In [39]:
arr[0]=42

In [40]:
print(arr)

[42  2  3  4  5]


In [41]:
print(x)

[42  2  3  4  5]


In [42]:
x[2]=4

In [43]:
print(x)

[42  2  4  4  5]


In [44]:
arr=np.append(arr,[7])

In [45]:
arr

array([42,  2,  4,  4,  5,  7])

In [46]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.append(arr1,arr2)

In [47]:
print(arr)

[1 2 3 4 5 6]


In [48]:
arr

array([1, 2, 3, 4, 5, 6])

In [50]:
arr

array([1, 2, 3, 4, 5, 6])

In [53]:
for i in arr:
    print(i)

1
2
3
4
5
6


In [55]:
for i in arr:
    print(i,end=' ')

1 2 3 4 5 6 

In [56]:
arr=np.array([[1,2,3],[4,5,6]])

In [57]:
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [58]:
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [59]:
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [63]:
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [64]:
for x in arr:
    for y in x:
        print(y)

[1 2 3]
[4 5 6]
[1 2 3]
[4 5 6]


In [68]:
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
1
2
3
4
5
6


In [69]:
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
1
2
3
4
5
6


In [71]:
arr=np.array([[1,2,3,4],[5,6,7,8]])

In [72]:
for x in np.nditer(arr[:,::2]):
    print(x)

1
3
5
7
