In [2]:
import numpy as np

In [12]:
print(np.__version__)

1.24.2


In [13]:
list1 = [1,2,3]
a=np.array(list1)
print(a)

[1 2 3]


In [14]:
print(a)

[1 2 3]


In [18]:
b=np.array([1,2,3,4,5])
print(b)

1


In [19]:
c = np.array([[1,2,3],[4,5,6]])

In [20]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
x = np.array([1,2,'sameer'])

In [24]:
x

array(['1', '2', 'sameer'], dtype='<U11')

In [28]:
x[2].dtype

dtype('<U6')

In [29]:
b[0].dtype

dtype('int32')

In [8]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=np.array([1,2,3,4])

In [9]:
a[0]

array([1, 2, 3, 4])

In [10]:
b[0]

1

In [11]:
a[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [12]:
b[3]

4

In [19]:
np.linspace(10,25,6)

array([10., 13., 16., 19., 22., 25.])

In [17]:
np.linspace(1,9,4)

array([1.        , 3.66666667, 6.33333333, 9.        ])

In [16]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [23]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [28]:
np.zeros((2,3,4,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [29]:
np.ones(4)

array([1., 1., 1., 1.])

In [31]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])